#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pid_file="/var/run/myscript.pid"

echo "$$" > "$pid_file"

cleanup() {
    rm -f "$pid_file"
    exit 0
}

term_handler() {
    echo "I hate the kill command"
    cleanup
}

int_handler() {
    echo "Y U no love me?!"
}

# Traps
trap term_handler SIGTERM
trap int_handler SIGINT
trap cleanup SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done

