#!/usr/bin/env bash
#display of all  process without use of ps
for pid in /proc/[0-9]*; do
    if [ -f "$pid/comm" ]; then
        name=$(cat "$pid/comm")
        if [[ "$name" == *bash* ]]; then
            echo "$(basename "$pid") $name"
        fi
    fi
done
